### ISSUE TITLE
Auto complete function

### ISSUE THREAD

**Issue by agch-dev** [bryant1410/Sublime-Text-3-Modula-2-Syntax#1]
Hi,
   I don't know why but the auto complete function uses the text that I have in the comments to suggest me words too. I don't like that cause the auto complete dropdown gets to crowded to easily. Do you think you can eliminate the comments form the text of the auto complete to search?

**Comment by bryant1410** [comment]
Hi. I recommend you to use [Sublime-Modula-2 plugin](https://github.com/harogaston/Sublime-Modula-2) instead of this one as its much more complete, so check it out and maybe the issue you mention is not present. This one is deprecated.

Please also note that Sublime-Modula-2 plugin has some caveats too, but it's open to contributions (and issues)  :smiley:
